fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.1.0'
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.1.0
          - prettier-plugin-svelte
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/crate-ci/typos
    rev: v1.8.1
    hooks:
      - id: typos
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        description: Format files with rustfmt.
        entry: bash -c 'cd src-tauri && cargo fmt -- --check'
        language: system
        files: \.rs$
        args: []
      # - id: cargo-deny
      #   name: cargo deny check
      #   description: Check cargo dependencies
      #   entry: bash -c 'cd src-tauri && cargo deny check'
      #   language: system
      #   files: \.rs$
      #   args: []
      - id: cargo-check
        name: cargo check
        description: Check the package for errors.
        entry: bash -c 'cd src-tauri && cargo check --all'
        language: system
        files: \.rs$
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        description: Lint rust sources
        entry: bash -c 'cd src-tauri && cargo clippy --all-targets --all-features --tests --benches -- -D warnings'
        language: system
        files: \.rs$
        pass_filenames: false
      - id: cargo-test
        name: cargo test
        description: unit test for the project
        entry: bash -c 'cd src-tauri && cargo test run --all-features'
        language: system
        files: \.rs$
        pass_filenames: false
