name: Build

on:
  push:

jobs:
  build:
    name: Build Tauri App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (ubuntu only)
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features

      - name: Install NPM packages
        run: npm install

      - name: Build App
        run: npm run tauri build
